# Generated by Django 3.0.5 on 2020-04-13 10:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('short', models.CharField(max_length=200)),
                ('desc', models.TextField(max_length=2000)),
                ('author', models.CharField(max_length=100)),
                ('category1', models.CharField(max_length=100)),
                ('category2', models.CharField(blank=True, max_length=100)),
                ('category3', models.CharField(blank=True, max_length=100)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=300)),
                ('short', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('category', models.CharField(max_length=100)),
            ],
        ),
    ]
