# Generated by Django 3.0.5 on 2020-04-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=300)),
                ('website', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField(max_length=2000)),
            ],
        ),
    ]
