# Generated by Django 3.0.5 on 2020-04-15 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image1',
            field=models.CharField(max_length=500),
        ),
    ]
